services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn stock_prediction_main.wsgi:application
    rootDir: backend-drf
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stock_prediction_main.settings
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY  
      - key: DEBUG
        value: "False"
